export const ROUTES = {
  AUTH: {
    LOGIN: '/(auth)/login',
    REGISTER: '/(auth)/register',
    FORGOT_PASSWORD: '/(auth)/forgot-password',
    VERIFY_ACCOUNT: '/(auth)/verify-account',
  },
  MAIN: {
    HOME: '/(main)/home',
    EMERGENCY: {
      INDEX: '/(main)/emergency',
      SOS: '/(main)/emergency/sos',
      ALERTS: '/(main)/emergency/alerts',
      CONTACTS: '/(main)/emergency/emergency-contacts',
      SERVICES: '/(main)/emergency/emergency-services',
    },
    RISK: {
      INDEX: '/(main)/risk',
      CURRENT: '/(main)/risk/current-risk',
      SAFE_ZONES: '/(main)/risk/safe-zones',
      EVACUATION: '/(main)/risk/evacuation-route',
      HAZARDS: '/(main)/risk/hazard-details',
      HISTORY: '/(main)/risk/risk-history',
    },
    AI: {
      INDEX: '/(main)/ai',
      CHAT: '/(main)/ai/chat',
      VOICE: '/(main)/ai/voice',
      REPORT: '/(main)/ai/report-disaster',
      IMAGE: '/(main)/ai/image-analysis',
      CONVERSATION: '/(main)/ai/conversation',
    },
    SAFETY: {
      INDEX: '/(main)/safety',
      SHELTERS: '/(main)/safety/shelters',
      SHELTER_DETAILS: '/(main)/safety/shelter-details',
      FAMILY: '/(main)/safety/family',
      FAMILY_MEMBER: '/(main)/safety/family-member',
      GUIDE: '/(main)/safety/safety-guide',
      FIRST_AID: '/(main)/safety/first-aid',
    },
    INCIDENTS: {
      INDEX: '/(main)/incidents',
      REPORT: '/(main)/incidents/report',
      MY_REPORTS: '/(main)/incidents/my-reports',
      DETAILS: '/(main)/incidents/report-details',
    },
    OFFLINE: {
      INDEX: '/(main)/offline',
      ALERTS: '/(main)/offline/offline-alerts',
      PENDING: '/(main)/offline/pending-sync',
      STATUS: '/(main)/offline/sync-status',
    },
    MAPS: {
      INDEX: '/(main)/maps',
      LIVE: '/(main)/maps/live-map',
      HAZARD: '/(main)/maps/hazard-map',
      SHELTER: '/(main)/maps/shelter-map',
      EVACUATION: '/(main)/maps/evacuation-map',
    },
    PROFILE: {
      INDEX: '/(main)/profile',
      DETAILS: '/(main)/profile/profile',
      SETTINGS: '/(main)/profile/settings',
      PERMISSIONS: '/(main)/profile/permissions',
      PRIVACY: '/(main)/profile/privacy',
    },
  },
  MODAL: {
    SOS_CONFIRMATION: '/modal/sos-confirmation',
    LOCATION_PERMISSION: '/modal/location-permission',
    REPORT_PREVIEW: '/modal/report-preview',
    EMERGENCY_ACTION: '/modal/emergency-action',
  },
} as const;
