export const FEATURE_FLAGS = {
  ENABLE_LORA_MESH: true,
  ENABLE_OFFLINE_AI_SYNTHESIZER: true,
  ENABLE_HIGH_PRECISION_GPS: true,
  ENABLE_BIOMETRIC_AUTH: true,
  ENABLE_VOICE_ASSISTANT: true,
  ENABLE_SATELLITE_OVERLAYS: false,
};
